
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '2D62959CE4080C7C47431A6B356EAAEC'
    
_lr_action_items = {'H1_E':([13,],[15,]),'STRING':([6,11,],[9,13,]),'TITLE_E':([9,],[12,]),'TITLE_O':([4,],[6,]),'HEAD_E':([12,],[14,]),'BODY_E':([15,],[16,]),'$end':([1,2,10,],[-1,0,-2,]),'HTML_E':([7,16,],[10,-4,]),'HEAD_O':([3,],[4,]),'H1_O':([8,],[11,]),'BODY_O':([5,14,],[8,-3,]),'HTML_O':([0,],[3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'body':([5,],[7,]),'head':([3,],[5,]),'document':([0,],[1,]),'init':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> document','init',1,'p_init','YACC_ply.py',6),
  ('document -> HTML_O head body HTML_E','document',4,'p_document','YACC_ply.py',8),
  ('head -> HEAD_O TITLE_O STRING TITLE_E HEAD_E','head',5,'p_head','YACC_ply.py',14),
  ('body -> BODY_O H1_O STRING H1_E BODY_E','body',5,'p_body','YACC_ply.py',19),
]
